import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Replacing stock geistSans font of nextjs to Inter
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

// commenting this since it's unneeded (I have new content)
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Lanz Malto | Next Blog App</title>
        {/* DaisyUI CDN for ui components */}
        <link
          href="https://cdn.jsdelivr.net/npm/daisyui@5"
          rel="stylesheet"
          type="text/css"
        />
      </head>
      <body className={`${inter.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
